version: "3.9"

services:
  database:
    image: postgres
    container_name: fin_api_database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
      - POSTGRES_USER=postgres

volumes:
  pgdata:
    driver: local
